version: 2
updates:
  # Maintain dependencies for Cargo - entire workspace
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      patch-updates:
        update-types:
          - "patch"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"
