doc-valid-idents = [
  # keep-sorted start
  "AllDifferent",
  "BatSat",
  "CaDiCaL",
  "MaxSAT",
  "ModRef",
  "RustSAT",
  "VeriPB",
  # keep-sorted end
  "..",
]
avoid-breaking-exported-api = false
