// !!! Auto-generated by codegen, do not edit manually !!!

#include <assert.h>

#include "rustsat.h"

void clause_counter(int lit, void *data) {
  if (!lit) {
    int *cnt = (int *)data;
    (*cnt)++;
  }
}

int main() {
  Bimander *bimander = bimander_new();
  assert(bimander_add(bimander, 1) == Ok);
  assert(bimander_add(bimander, 2) == Ok);
  assert(bimander_add(bimander, 3) == Ok);
  assert(bimander_add(bimander, 4) == Ok);
  uint32_t n_used = 4;
  uint32_t n_clauses = 0;
  bimander_encode(bimander, &n_used, &clause_counter, &n_clauses);
  bimander_drop(bimander);
  assert(n_used == 5);
  assert(n_clauses == 10);
  return 0;
}
