// !!! Auto-generated by codegen, do not edit manually !!!

#include <assert.h>

#include "rustsat.h"

int main() {
  Bimander *bimander = bimander_new();
  assert(bimander != NULL);
  bimander_drop(bimander);
  return 0;
}
