// !!! Auto-generated by codegen, do not edit manually !!!

#include <assert.h>

#include "rustsat.h"

int main() {
  BinaryAdder *bin_adder = bin_adder_new();
  assert(bin_adder != NULL);
  bin_adder_drop(bin_adder);
  return 0;
}
