// !!! Auto-generated by codegen, do not edit manually !!!

#include <assert.h>

#include "rustsat.h"

int main() {
  Bitwise *bitwise = bitwise_new();
  assert(bitwise != NULL);
  bitwise_drop(bitwise);
  return 0;
}
