// !!! Auto-generated by codegen, do not edit manually !!!

#include <assert.h>

#include "rustsat.h"

void clause_counter(int lit, void *data) {
  if (!lit) {
    int *cnt = (int *)data;
    (*cnt)++;
  }
}

int main() {
  Bitwise *bitwise = bitwise_new();
  assert(bitwise_add(bitwise, 1) == Ok);
  assert(bitwise_add(bitwise, 2) == Ok);
  assert(bitwise_add(bitwise, 3) == Ok);
  assert(bitwise_add(bitwise, 4) == Ok);
  uint32_t n_used = 4;
  uint32_t n_clauses = 0;
  bitwise_encode(bitwise, &n_used, &clause_counter, &n_clauses);
  bitwise_drop(bitwise);
  assert(n_used == 6);
  assert(n_clauses == 8);
  return 0;
}
