// !!! Auto-generated by codegen, do not edit manually !!!

#include <assert.h>

#include "rustsat.h"

int main() {
  Commander *commander = commander_new();
  assert(commander != NULL);
  commander_drop(commander);
  return 0;
}
