// !!! Auto-generated by codegen, do not edit manually !!!

#include <assert.h>

#include "rustsat.h"

int main() {
  DynamicPolyWatchdog *dpw = dpw_new();
  assert(dpw != NULL);
  dpw_drop(dpw);
  return 0;
}
