// !!! Auto-generated by codegen, do not edit manually !!!

#include <assert.h>

#include "rustsat.h"

void clause_counter(int lit, void *data) {
  if (!lit) {
    int *cnt = (int *)data;
    (*cnt)++;
  }
}

void output_collector(size_t val, int lit, void *data) {
  (void)val;
  (void)data;
  assert(lit != 0);
}

int main() {
  GeneralizedTotalizer *gte = gte_new();
  assert(gte_add(gte, 1, 1) == Ok);
  assert(gte_add(gte, 2, 2) == Ok);
  uint32_t n_used = 2;
  uint32_t n_clauses = 0;
  gte_encode_ub(gte, 0, 3, &n_used, &clause_counter, &n_clauses);
  int lit = 0;
  assert(gte_get_output(gte, 1, &lit) == Ok);
  assert(lit != 0);
  assert(gte_get_outputs(gte, &output_collector, NULL) == Ok);
  gte_drop(gte);
  return 0;
}
