// !!! Auto-generated by codegen, do not edit manually !!!

#include <assert.h>

#include "rustsat.h"

int main() {
  GeneralizedTotalizer *gte = gte_new();
  assert(gte != NULL);
  gte_drop(gte);
  return 0;
}
