// !!! Auto-generated by codegen, do not edit manually !!!

#include <assert.h>

#include "rustsat.h"

void clause_counter(int lit, void *data) {
  if (!lit) {
    int *cnt = (int *)data;
    (*cnt)++;
  }
}

int main() {
  GeneralizedTotalizer *gte = gte_new();
  assert(gte_add(gte, 1, 1) == Ok);
  assert(gte_add(gte, 2, 2) == Ok);
  assert(gte_add(gte, 3, 3) == Ok);
  assert(gte_add(gte, 4, 4) == Ok);
  uint32_t n_used = 4;
  uint32_t n_clauses = 0;
  gte_encode_ub(gte, 0, 10, &n_used, &clause_counter, &n_clauses);
  gte_drop(gte);
  assert(n_used == 24);
  assert(n_clauses == 25);
  return 0;
}
