// !!! Auto-generated by codegen, do not edit manually !!!

#include <assert.h>

#include "rustsat.h"

int main() {
  Ladder *ladder = ladder_new();
  assert(ladder != NULL);
  ladder_drop(ladder);
  return 0;
}
