// !!! Auto-generated by codegen, do not edit manually !!!

#include <assert.h>

#include "rustsat.h"

void clause_counter(int lit, void *data) {
  if (!lit) {
    int *cnt = (int *)data;
    (*cnt)++;
  }
}

int main() {
  Ladder *ladder = ladder_new();
  assert(ladder_add(ladder, 1) == Ok);
  assert(ladder_add(ladder, 2) == Ok);
  assert(ladder_add(ladder, 3) == Ok);
  assert(ladder_add(ladder, 4) == Ok);
  uint32_t n_used = 4;
  uint32_t n_clauses = 0;
  ladder_encode(ladder, &n_used, &clause_counter, &n_clauses);
  ladder_drop(ladder);
  assert(n_used == 7);
  assert(n_clauses == 8);
  return 0;
}
