// !!! Auto-generated by codegen, do not edit manually !!!

#include <assert.h>

#include "rustsat.h"

void clause_counter(int lit, void *data) {
  if (!lit) {
    int *cnt = (int *)data;
    (*cnt)++;
  }
}

int main() {
  Pairwise *pairwise = pairwise_new();
  assert(pairwise_add(pairwise, 1) == Ok);
  assert(pairwise_add(pairwise, 2) == Ok);
  assert(pairwise_add(pairwise, 3) == Ok);
  assert(pairwise_add(pairwise, 4) == Ok);
  uint32_t n_used = 4;
  uint32_t n_clauses = 0;
  pairwise_encode(pairwise, &n_used, &clause_counter, &n_clauses);
  pairwise_drop(pairwise);
  assert(n_used == 4);
  assert(n_clauses == 6);
  return 0;
}
