// !!! Auto-generated by codegen, do not edit manually !!!

#include <assert.h>

#include "rustsat.h"

int main() {
  Pairwise *pairwise = pairwise_new();
  assert(pairwise != NULL);
  pairwise_drop(pairwise);
  return 0;
}
