// !!! Auto-generated by codegen, do not edit manually !!!

#include <assert.h>

#include "rustsat.h"

int main() {
  Totalizer *tot = tot_new();
  assert(tot != NULL);
  tot_drop(tot);
  return 0;
}
