// !!! Auto-generated by codegen, do not edit manually !!!

#include <assert.h>

#include "rustsat.h"

void clause_counter(int lit, void *data) {
  if (!lit) {
    int *cnt = (int *)data;
    (*cnt)++;
  }
}

void output_collector(size_t val, int lit, void *data) {
  (void)val;
  (void)data;
  assert(lit != 0);
}

int main() {
  Totalizer *tot = tot_new();
  assert(tot_add(tot, 1) == Ok);
  assert(tot_add(tot, 2) == Ok);
  uint32_t n_used = 2;
  uint32_t n_clauses = 0;
  tot_encode_ub(tot, 0, 2, &n_used, &clause_counter, &n_clauses);
  int lit = 0;
  assert(tot_get_output(tot, 1, &lit) == Ok);
  assert(lit != 0);
  assert(tot_get_outputs(tot, &output_collector, NULL) == Ok);
  tot_drop(tot);
  return 0;
}
