// !!! Auto-generated by codegen, do not edit manually !!!

#include <assert.h>

#include "rustsat.h"

void clause_counter(int lit, void *data) {
  if (!lit) {
    int *cnt = (int *)data;
    (*cnt)++;
  }
}

int main() {
  TwoProduct *twoproduct = twoproduct_new();
  assert(twoproduct_add(twoproduct, 1) == Ok);
  assert(twoproduct_add(twoproduct, 2) == Ok);
  assert(twoproduct_add(twoproduct, 3) == Ok);
  assert(twoproduct_add(twoproduct, 4) == Ok);
  uint32_t n_used = 4;
  uint32_t n_clauses = 0;
  twoproduct_encode(twoproduct, &n_used, &clause_counter, &n_clauses);
  twoproduct_drop(twoproduct);
  assert(n_used == 8);
  assert(n_clauses == 10);
  return 0;
}
