// !!! Auto-generated by codegen, do not edit manually !!!

#include <assert.h>

#include "rustsat.h"

int main() {
  TwoProduct *twoproduct = twoproduct_new();
  assert(twoproduct != NULL);
  twoproduct_drop(twoproduct);
  return 0;
}
