use rustsat::{
    instances::CNF,
    lit,
    solvers::{ipasir::IpasirSolver, IncrementalSolve, SolverResult},
    types::Lit,
};

#[test]
fn cnf_implications() {
    let a0 = lit![0];
    let a1 = lit![1];
    let b0 = lit![3];
    let b1 = lit![4];

    let mut cnf = CNF::new();
    cnf.add_lit_impl_lit(a0, b0);
    let mut solver = IpasirSolver::new();
    cnf.add_to_solver(&mut solver);
    let ret = solver.solve_assumps(vec![a0, b0]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![a0, !b0]).unwrap();
    assert_eq!(ret, SolverResult::UNSAT);
    let ret = solver.solve_assumps(vec![!a0, b0]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, !b0]).unwrap();
    assert_eq!(ret, SolverResult::SAT);

    let mut cnf = CNF::new();
    cnf.add_lit_impl_or(a0, vec![b0, b1]);
    let mut solver = IpasirSolver::new();
    cnf.add_to_solver(&mut solver);
    let ret = solver.solve_assumps(vec![a0, b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![a0, b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![a0, !b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![a0, !b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::UNSAT);
    let ret = solver.solve_assumps(vec![!a0, b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, !b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, !b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);

    let mut cnf = CNF::new();
    cnf.add_lit_impl_and(a0, vec![b0, b1]);
    let mut solver = IpasirSolver::new();
    cnf.add_to_solver(&mut solver);
    let ret = solver.solve_assumps(vec![a0, b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![a0, b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::UNSAT);
    let ret = solver.solve_assumps(vec![a0, !b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::UNSAT);
    let ret = solver.solve_assumps(vec![a0, !b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::UNSAT);
    let ret = solver.solve_assumps(vec![!a0, b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, !b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, !b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);

    let mut cnf = CNF::new();
    cnf.add_and_impl_lit(vec![a0, a1], b0);
    let mut solver = IpasirSolver::new();
    cnf.add_to_solver(&mut solver);
    let ret = solver.solve_assumps(vec![a0, a1, b0]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![a0, a1, !b0]).unwrap();
    assert_eq!(ret, SolverResult::UNSAT);
    let ret = solver.solve_assumps(vec![a0, !a1, b0]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![a0, !a1, !b0]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, a1, b0]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, a1, !b0]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, !a1, b0]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, !a1, !b0]).unwrap();
    assert_eq!(ret, SolverResult::SAT);

    let mut cnf = CNF::new();
    cnf.add_or_impl_lit(vec![a0, a1], b0);
    let mut solver = IpasirSolver::new();
    cnf.add_to_solver(&mut solver);
    let ret = solver.solve_assumps(vec![a0, a1, b0]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![a0, a1, !b0]).unwrap();
    assert_eq!(ret, SolverResult::UNSAT);
    let ret = solver.solve_assumps(vec![a0, !a1, b0]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![a0, !a1, !b0]).unwrap();
    assert_eq!(ret, SolverResult::UNSAT);
    let ret = solver.solve_assumps(vec![!a0, a1, b0]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, a1, !b0]).unwrap();
    assert_eq!(ret, SolverResult::UNSAT);
    let ret = solver.solve_assumps(vec![!a0, !a1, b0]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, !a1, !b0]).unwrap();
    assert_eq!(ret, SolverResult::SAT);

    let mut cnf = CNF::new();
    cnf.add_and_impl_or(vec![a0, a1], vec![b0, b1]);
    let mut solver = IpasirSolver::new();
    cnf.add_to_solver(&mut solver);
    let ret = solver.solve_assumps(vec![a0, a1, b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![a0, a1, b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![a0, a1, !b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![a0, a1, !b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::UNSAT);
    let ret = solver.solve_assumps(vec![a0, !a1, b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![a0, !a1, b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![a0, !a1, !b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![a0, !a1, !b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, a1, b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, a1, b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, a1, !b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, a1, !b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, !a1, b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, !a1, b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, !a1, !b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, !a1, !b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);

    let mut cnf = CNF::new();
    cnf.add_or_impl_or(vec![a0, a1], vec![b0, b1]);
    let mut solver = IpasirSolver::new();
    cnf.add_to_solver(&mut solver);
    let ret = solver.solve_assumps(vec![a0, a1, b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![a0, a1, b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![a0, a1, !b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![a0, a1, !b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::UNSAT);
    let ret = solver.solve_assumps(vec![a0, !a1, b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![a0, !a1, b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![a0, !a1, !b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![a0, !a1, !b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::UNSAT);
    let ret = solver.solve_assumps(vec![!a0, a1, b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, a1, b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, a1, !b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, a1, !b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::UNSAT);
    let ret = solver.solve_assumps(vec![!a0, !a1, b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, !a1, b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, !a1, !b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, !a1, !b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);

    let mut cnf = CNF::new();
    cnf.add_or_impl_and(vec![a0, a1], vec![b0, b1]);
    let mut solver = IpasirSolver::new();
    cnf.add_to_solver(&mut solver);
    let ret = solver.solve_assumps(vec![a0, a1, b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![a0, a1, b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::UNSAT);
    let ret = solver.solve_assumps(vec![a0, a1, !b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::UNSAT);
    let ret = solver.solve_assumps(vec![a0, a1, !b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::UNSAT);
    let ret = solver.solve_assumps(vec![a0, !a1, b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![a0, !a1, b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::UNSAT);
    let ret = solver.solve_assumps(vec![a0, !a1, !b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::UNSAT);
    let ret = solver.solve_assumps(vec![a0, !a1, !b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::UNSAT);
    let ret = solver.solve_assumps(vec![!a0, a1, b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, a1, b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::UNSAT);
    let ret = solver.solve_assumps(vec![!a0, a1, !b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::UNSAT);
    let ret = solver.solve_assumps(vec![!a0, a1, !b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::UNSAT);
    let ret = solver.solve_assumps(vec![!a0, !a1, b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, !a1, b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, !a1, !b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, !a1, !b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);

    let mut cnf = CNF::new();
    cnf.add_and_impl_and(vec![a0, a1], vec![b0, b1]);
    let mut solver = IpasirSolver::new();
    cnf.add_to_solver(&mut solver);
    let ret = solver.solve_assumps(vec![a0, a1, b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![a0, a1, b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::UNSAT);
    let ret = solver.solve_assumps(vec![a0, a1, !b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::UNSAT);
    let ret = solver.solve_assumps(vec![a0, a1, !b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::UNSAT);
    let ret = solver.solve_assumps(vec![a0, !a1, b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![a0, !a1, b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![a0, !a1, !b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![a0, !a1, !b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, a1, b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, a1, b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, a1, !b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, a1, !b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, !a1, b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, !a1, b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, !a1, !b0, b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
    let ret = solver.solve_assumps(vec![!a0, !a1, !b0, !b1]).unwrap();
    assert_eq!(ret, SolverResult::SAT);
}
