// Auto-generated by codegen, do not edit manually

use std::ffi::{c_int, c_void};

use rustsat::{
    encodings::am1::{Bitwise, Encode, Ladder, Pairwise},
    types::Lit,
};

use super::{Bimander, CClauseCollector, ClauseCollector, Commander, MaybeError, VarManager};

/// Creates a new [`Pairwise`] at-most-one encoding
#[no_mangle]
#[allow(clippy::missing_safety_doc)]
pub unsafe extern "C" fn pairwise_new() -> *mut Pairwise {
    Box::into_raw(Box::default())
}

/// Frees the memory associated with a [`Pairwise`]
///
/// # Safety
///
/// `pairwise` must be a return value of [`pairwise_new`] and cannot be used afterwards again.
#[no_mangle]
pub unsafe extern "C" fn pairwise_drop(pairwise: *mut Pairwise) {
    drop(Box::from_raw(pairwise));
}

/// Adds a new input literal to a [`Pairwise`] encoding
///
/// # Errors
///
/// - If `lit` is not a valid IPASIR-style literal (e.g., `lit = 0`),
///     [`MaybeError::InvalidLiteral`] is returned
///
/// # Safety
///
/// `pairwise` must be a return value of [`pairwise_new`] that [`pairwise_drop`] has not yet been called on.
#[no_mangle]
pub unsafe extern "C" fn pairwise_add(pairwise: *mut Pairwise, lit: c_int) -> MaybeError {
    let Ok(lit) = Lit::from_ipasir(lit) else {
        return MaybeError::InvalidLiteral;
    };
    (*pairwise).extend([lit]);
    MaybeError::Ok
}

/// Builds the [`Pairwise`] at-most-one encoding
///
/// Clauses are returned via the `collector`. The `collector` function should expect clauses to be
/// passed similarly to `ipasir_add`, as a 0-terminated sequence of literals where the literals are
/// passed as the first argument and the `collector_data` as a second.
///
/// `n_vars_used` must be the number of variables already used and will be incremented by the
/// number of variables used up in the encoding.
///
/// # Safety
///
/// `pairwise` must be a return value of [`pairwise_new`] that [`pairwise_drop`] has not yet been called on.
#[allow(clippy::missing_panics_doc)]
#[no_mangle]
pub unsafe extern "C" fn pairwise_encode(
    pairwise: *mut Pairwise,
    n_vars_used: &mut u32,
    collector: CClauseCollector,
    collector_data: *mut c_void,
) {
    let mut collector = ClauseCollector::new(collector, collector_data);
    let mut var_manager = VarManager::new(n_vars_used);
    (*pairwise)
        .encode(&mut collector, &mut var_manager)
        .expect("CClauseCollector cannot report out of memory");
}

/// Creates a new [`Ladder`] at-most-one encoding
#[no_mangle]
#[allow(clippy::missing_safety_doc)]
pub unsafe extern "C" fn ladder_new() -> *mut Ladder {
    Box::into_raw(Box::default())
}

/// Frees the memory associated with a [`Ladder`]
///
/// # Safety
///
/// `ladder` must be a return value of [`ladder_new`] and cannot be used afterwards again.
#[no_mangle]
pub unsafe extern "C" fn ladder_drop(ladder: *mut Ladder) {
    drop(Box::from_raw(ladder));
}

/// Adds a new input literal to a [`Ladder`] encoding
///
/// # Errors
///
/// - If `lit` is not a valid IPASIR-style literal (e.g., `lit = 0`),
///     [`MaybeError::InvalidLiteral`] is returned
///
/// # Safety
///
/// `ladder` must be a return value of [`ladder_new`] that [`ladder_drop`] has not yet been called on.
#[no_mangle]
pub unsafe extern "C" fn ladder_add(ladder: *mut Ladder, lit: c_int) -> MaybeError {
    let Ok(lit) = Lit::from_ipasir(lit) else {
        return MaybeError::InvalidLiteral;
    };
    (*ladder).extend([lit]);
    MaybeError::Ok
}

/// Builds the [`Ladder`] at-most-one encoding
///
/// Clauses are returned via the `collector`. The `collector` function should expect clauses to be
/// passed similarly to `ipasir_add`, as a 0-terminated sequence of literals where the literals are
/// passed as the first argument and the `collector_data` as a second.
///
/// `n_vars_used` must be the number of variables already used and will be incremented by the
/// number of variables used up in the encoding.
///
/// # Safety
///
/// `ladder` must be a return value of [`ladder_new`] that [`ladder_drop`] has not yet been called on.
#[allow(clippy::missing_panics_doc)]
#[no_mangle]
pub unsafe extern "C" fn ladder_encode(
    ladder: *mut Ladder,
    n_vars_used: &mut u32,
    collector: CClauseCollector,
    collector_data: *mut c_void,
) {
    let mut collector = ClauseCollector::new(collector, collector_data);
    let mut var_manager = VarManager::new(n_vars_used);
    (*ladder)
        .encode(&mut collector, &mut var_manager)
        .expect("CClauseCollector cannot report out of memory");
}

/// Creates a new [`Bitwise`] at-most-one encoding
#[no_mangle]
#[allow(clippy::missing_safety_doc)]
pub unsafe extern "C" fn bitwise_new() -> *mut Bitwise {
    Box::into_raw(Box::default())
}

/// Frees the memory associated with a [`Bitwise`]
///
/// # Safety
///
/// `bitwise` must be a return value of [`bitwise_new`] and cannot be used afterwards again.
#[no_mangle]
pub unsafe extern "C" fn bitwise_drop(bitwise: *mut Bitwise) {
    drop(Box::from_raw(bitwise));
}

/// Adds a new input literal to a [`Bitwise`] encoding
///
/// # Errors
///
/// - If `lit` is not a valid IPASIR-style literal (e.g., `lit = 0`),
///     [`MaybeError::InvalidLiteral`] is returned
///
/// # Safety
///
/// `bitwise` must be a return value of [`bitwise_new`] that [`bitwise_drop`] has not yet been called on.
#[no_mangle]
pub unsafe extern "C" fn bitwise_add(bitwise: *mut Bitwise, lit: c_int) -> MaybeError {
    let Ok(lit) = Lit::from_ipasir(lit) else {
        return MaybeError::InvalidLiteral;
    };
    (*bitwise).extend([lit]);
    MaybeError::Ok
}

/// Builds the [`Bitwise`] at-most-one encoding
///
/// Clauses are returned via the `collector`. The `collector` function should expect clauses to be
/// passed similarly to `ipasir_add`, as a 0-terminated sequence of literals where the literals are
/// passed as the first argument and the `collector_data` as a second.
///
/// `n_vars_used` must be the number of variables already used and will be incremented by the
/// number of variables used up in the encoding.
///
/// # Safety
///
/// `bitwise` must be a return value of [`bitwise_new`] that [`bitwise_drop`] has not yet been called on.
#[allow(clippy::missing_panics_doc)]
#[no_mangle]
pub unsafe extern "C" fn bitwise_encode(
    bitwise: *mut Bitwise,
    n_vars_used: &mut u32,
    collector: CClauseCollector,
    collector_data: *mut c_void,
) {
    let mut collector = ClauseCollector::new(collector, collector_data);
    let mut var_manager = VarManager::new(n_vars_used);
    (*bitwise)
        .encode(&mut collector, &mut var_manager)
        .expect("CClauseCollector cannot report out of memory");
}

/// Creates a new [`Commander`] at-most-one encoding
#[no_mangle]
#[allow(clippy::missing_safety_doc)]
pub unsafe extern "C" fn commander_new() -> *mut Commander {
    Box::into_raw(Box::default())
}

/// Frees the memory associated with a [`Commander`]
///
/// # Safety
///
/// `commander` must be a return value of [`commander_new`] and cannot be used afterwards again.
#[no_mangle]
pub unsafe extern "C" fn commander_drop(commander: *mut Commander) {
    drop(Box::from_raw(commander));
}

/// Adds a new input literal to a [`Commander`] encoding
///
/// # Errors
///
/// - If `lit` is not a valid IPASIR-style literal (e.g., `lit = 0`),
///     [`MaybeError::InvalidLiteral`] is returned
///
/// # Safety
///
/// `commander` must be a return value of [`commander_new`] that [`commander_drop`] has not yet been called on.
#[no_mangle]
pub unsafe extern "C" fn commander_add(commander: *mut Commander, lit: c_int) -> MaybeError {
    let Ok(lit) = Lit::from_ipasir(lit) else {
        return MaybeError::InvalidLiteral;
    };
    (*commander).0.extend([lit]);
    MaybeError::Ok
}

/// Builds the [`Commander`] at-most-one encoding
///
/// Clauses are returned via the `collector`. The `collector` function should expect clauses to be
/// passed similarly to `ipasir_add`, as a 0-terminated sequence of literals where the literals are
/// passed as the first argument and the `collector_data` as a second.
///
/// `n_vars_used` must be the number of variables already used and will be incremented by the
/// number of variables used up in the encoding.
///
/// # Safety
///
/// `commander` must be a return value of [`commander_new`] that [`commander_drop`] has not yet been called on.
#[allow(clippy::missing_panics_doc)]
#[no_mangle]
pub unsafe extern "C" fn commander_encode(
    commander: *mut Commander,
    n_vars_used: &mut u32,
    collector: CClauseCollector,
    collector_data: *mut c_void,
) {
    let mut collector = ClauseCollector::new(collector, collector_data);
    let mut var_manager = VarManager::new(n_vars_used);
    (*commander)
        .0
        .encode(&mut collector, &mut var_manager)
        .expect("CClauseCollector cannot report out of memory");
}

/// Creates a new [`Bimander`] at-most-one encoding
#[no_mangle]
#[allow(clippy::missing_safety_doc)]
pub unsafe extern "C" fn bimander_new() -> *mut Bimander {
    Box::into_raw(Box::default())
}

/// Frees the memory associated with a [`Bimander`]
///
/// # Safety
///
/// `bimander` must be a return value of [`bimander_new`] and cannot be used afterwards again.
#[no_mangle]
pub unsafe extern "C" fn bimander_drop(bimander: *mut Bimander) {
    drop(Box::from_raw(bimander));
}

/// Adds a new input literal to a [`Bimander`] encoding
///
/// # Errors
///
/// - If `lit` is not a valid IPASIR-style literal (e.g., `lit = 0`),
///     [`MaybeError::InvalidLiteral`] is returned
///
/// # Safety
///
/// `bimander` must be a return value of [`bimander_new`] that [`bimander_drop`] has not yet been called on.
#[no_mangle]
pub unsafe extern "C" fn bimander_add(bimander: *mut Bimander, lit: c_int) -> MaybeError {
    let Ok(lit) = Lit::from_ipasir(lit) else {
        return MaybeError::InvalidLiteral;
    };
    (*bimander).0.extend([lit]);
    MaybeError::Ok
}

/// Builds the [`Bimander`] at-most-one encoding
///
/// Clauses are returned via the `collector`. The `collector` function should expect clauses to be
/// passed similarly to `ipasir_add`, as a 0-terminated sequence of literals where the literals are
/// passed as the first argument and the `collector_data` as a second.
///
/// `n_vars_used` must be the number of variables already used and will be incremented by the
/// number of variables used up in the encoding.
///
/// # Safety
///
/// `bimander` must be a return value of [`bimander_new`] that [`bimander_drop`] has not yet been called on.
#[allow(clippy::missing_panics_doc)]
#[no_mangle]
pub unsafe extern "C" fn bimander_encode(
    bimander: *mut Bimander,
    n_vars_used: &mut u32,
    collector: CClauseCollector,
    collector_data: *mut c_void,
) {
    let mut collector = ClauseCollector::new(collector, collector_data);
    let mut var_manager = VarManager::new(n_vars_used);
    (*bimander)
        .0
        .encode(&mut collector, &mut var_manager)
        .expect("CClauseCollector cannot report out of memory");
}

#[cfg(all(test, not(target_os = "windows")))]
mod tests {
    use inline_c::assert_c;

    #[test]
    fn pairwise_new_drop() {
        (assert_c! {
            #include <assert.h>
            #include "rustsat.h"

            int main() {
                Pairwise *pairwise = pairwise_new();
                assert(pairwise != NULL);
                pairwise_drop(pairwise);
                return 0;
            }
        })
        .success();
    }

    #[test]
    fn pairwise_basic() {
        (assert_c! {
            #include <assert.h>
            #include "rustsat.h"

            void clause_counter(int lit, void *data) {
                if (!lit) {
                    int *cnt = (int *)data;
                    (*cnt)++;
                }
            }

            int main() {
                Pairwise *pairwise = pairwise_new();
                assert(pairwise_add(pairwise, 1) == Ok);
                assert(pairwise_add(pairwise, 2) == Ok);
                assert(pairwise_add(pairwise, 3) == Ok);
                assert(pairwise_add(pairwise, 4) == Ok);
                uint32_t n_used = 4;
                uint32_t n_clauses = 0;
                pairwise_encode(pairwise, &n_used, &clause_counter, &n_clauses);
                pairwise_drop(pairwise);
                assert(n_used == 4);
                assert(n_clauses == 6);
                return 0;
            }
        })
        .success();
    }

    #[test]
    fn ladder_new_drop() {
        (assert_c! {
            #include <assert.h>
            #include "rustsat.h"

            int main() {
                Ladder *ladder = ladder_new();
                assert(ladder != NULL);
                ladder_drop(ladder);
                return 0;
            }
        })
        .success();
    }

    #[test]
    fn ladder_basic() {
        (assert_c! {
            #include <assert.h>
            #include "rustsat.h"

            void clause_counter(int lit, void *data) {
                if (!lit) {
                    int *cnt = (int *)data;
                    (*cnt)++;
                }
            }

            int main() {
                Ladder *ladder = ladder_new();
                assert(ladder_add(ladder, 1) == Ok);
                assert(ladder_add(ladder, 2) == Ok);
                assert(ladder_add(ladder, 3) == Ok);
                assert(ladder_add(ladder, 4) == Ok);
                uint32_t n_used = 4;
                uint32_t n_clauses = 0;
                ladder_encode(ladder, &n_used, &clause_counter, &n_clauses);
                ladder_drop(ladder);
                assert(n_used == 7);
                assert(n_clauses == 8);
                return 0;
            }
        })
        .success();
    }

    #[test]
    fn bitwise_new_drop() {
        (assert_c! {
            #include <assert.h>
            #include "rustsat.h"

            int main() {
                Bitwise *bitwise = bitwise_new();
                assert(bitwise != NULL);
                bitwise_drop(bitwise);
                return 0;
            }
        })
        .success();
    }

    #[test]
    fn bitwise_basic() {
        (assert_c! {
            #include <assert.h>
            #include "rustsat.h"

            void clause_counter(int lit, void *data) {
                if (!lit) {
                    int *cnt = (int *)data;
                    (*cnt)++;
                }
            }

            int main() {
                Bitwise *bitwise = bitwise_new();
                assert(bitwise_add(bitwise, 1) == Ok);
                assert(bitwise_add(bitwise, 2) == Ok);
                assert(bitwise_add(bitwise, 3) == Ok);
                assert(bitwise_add(bitwise, 4) == Ok);
                uint32_t n_used = 4;
                uint32_t n_clauses = 0;
                bitwise_encode(bitwise, &n_used, &clause_counter, &n_clauses);
                bitwise_drop(bitwise);
                assert(n_used == 6);
                assert(n_clauses == 8);
                return 0;
            }
        })
        .success();
    }

    #[test]
    fn commander_new_drop() {
        (assert_c! {
            #include <assert.h>
            #include "rustsat.h"

            int main() {
                Commander *commander = commander_new();
                assert(commander != NULL);
                commander_drop(commander);
                return 0;
            }
        })
        .success();
    }

    #[test]
    fn commander_basic() {
        (assert_c! {
            #include <assert.h>
            #include "rustsat.h"

            void clause_counter(int lit, void *data) {
                if (!lit) {
                    int *cnt = (int *)data;
                    (*cnt)++;
                }
            }

            int main() {
                Commander *commander = commander_new();
                assert(commander_add(commander, 1) == Ok);
                assert(commander_add(commander, 2) == Ok);
                assert(commander_add(commander, 3) == Ok);
                assert(commander_add(commander, 4) == Ok);
                uint32_t n_used = 4;
                uint32_t n_clauses = 0;
                commander_encode(commander, &n_used, &clause_counter, &n_clauses);
                commander_drop(commander);
                assert(n_used == 5);
                assert(n_clauses == 10);
                return 0;
            }
        })
        .success();
    }

    #[test]
    fn bimander_new_drop() {
        (assert_c! {
            #include <assert.h>
            #include "rustsat.h"

            int main() {
                Bimander *bimander = bimander_new();
                assert(bimander != NULL);
                bimander_drop(bimander);
                return 0;
            }
        })
        .success();
    }

    #[test]
    fn bimander_basic() {
        (assert_c! {
            #include <assert.h>
            #include "rustsat.h"

            void clause_counter(int lit, void *data) {
                if (!lit) {
                    int *cnt = (int *)data;
                    (*cnt)++;
                }
            }

            int main() {
                Bimander *bimander = bimander_new();
                assert(bimander_add(bimander, 1) == Ok);
                assert(bimander_add(bimander, 2) == Ok);
                assert(bimander_add(bimander, 3) == Ok);
                assert(bimander_add(bimander, 4) == Ok);
                uint32_t n_used = 4;
                uint32_t n_clauses = 0;
                bimander_encode(bimander, &n_used, &clause_counter, &n_clauses);
                bimander_drop(bimander);
                assert(n_used == 5);
                assert(n_clauses == 10);
                return 0;
            }
        })
        .success();
    }
}
