experimental = ['setup-scripts']

[scripts.setup.capi-tests]
command = ['bash', 'scripts/setup-capi-tests.sh']

[profile.default]
final-status-level = "slow"

[[profile.default.scripts]]
filter = 'package(rustsat-capi)'
setup = 'capi-tests'

# this test isn't for a crash, but for a deadlock if stdout isn't properly processed
[[profile.default.overrides]]
filter = 'package(rustsat) and binary(external_solver) and test(deadlock)'
slow-timeout = { period = "30s", terminate-after = 2 }

[profile.ci]
inherits = "default"
fail-fast = false

[profile.git-hook]
inherits = "default"
fail-fast = false
slow-timeout = { period = "10s", terminate-after = 1, on-timeout = "pass" }
