[project]
name = "rustsat"
requires-python = ">=3.7"
dynamic = ["version"]

[project.urls]
Documentation = "https://christophjabs.info/rustsat/pyapi/"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
python-source = "python"
