name: BatSat

on:
  push:
    branches: [ "main", "next-major" ]
  pull_request:
    branches: [ "main", "next-major" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    name: Build and test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "build-test"
      - name: Install latest nextest release
        uses: taiki-e/install-action@nextest
      - name: Cargo build
        run: cargo build -p rustsat-batsat --verbose
      - name: Run tests
        run: cargo nextest run --profile ci -p rustsat-batsat --verbose
