name: CI
on:
  push:
    branches: ["main", "next-major"]
  pull_request:
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUSTDOCFLAGS: -Dwarnings
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci-everything:
    name: All CI stages
    runs-on: self-hosted
    needs:
      - tests
      - msrv-build
      - wasm-check
      - code-quality
      - python-api
      - doc
      - cadical-each-feature
      - kissat-each-feature
    if: ${{ always() }} # Run this job even if a dependency has failed.
    steps:
      - name: Job outcomes
        run: |
          echo "🧪 Workspace tests: ${{ needs.tests.result }}"
          echo "🏗️ MSRV build: ${{ needs.msrv-build.result }}"
          echo "🏄 WASM check: ${{ needs.wasm-check.result }}"
          echo "✨ Code Quality: ${{ needs.code-quality.result }}"
          echo "🐍 Python API: ${{ needs.python-api.result }}"
          echo "📑 Check documentation: ${{ needs.doc.result }}"
          echo "🧪 CaDiCaL test each feature: ${{ needs.cadical-each-feature.result }}"
          echo "🧪 Kissat test each feature: ${{ needs.kissat-each-feature.result }}"
      # Fail this required job if any of its dependent jobs have failed.
      #
      # Do not attempt to consolidate these steps into one step, it won't work.
      # Multi-line `if` clauses are not evaluated properly.
      - if: ${{ needs.tests.result == 'failure' }}
        run: exit 1
      - if: ${{ needs.msrv-build.result == 'failure' }}
        run: exit 1
      - if: ${{ needs.wasm-check.result == 'failure' }}
        run: exit 1
      - if: ${{ needs.code-quality.result != 'success' }}
        run: exit 1
      - if: ${{ needs.python-api.result == 'failure' }}
        run: exit 1
      - if: ${{ needs.doc.result == 'failure' }}
        run: exit 1
      - if: ${{ needs.cadical-each-feature.result == 'failure' }}
        run: exit 1
      - if: ${{ needs.kissat-each-feature.result == 'failure' }}
        run: exit 1
  dev-deps:
    name: 🏗️ Dev dependencies
    runs-on: [self-hosted, nix]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: 🏗️ Build dev dependencies
        run: nix build .#devDeps
  tests:
    name: 🧪 Workspace tests
    runs-on: [self-hosted, nix]
    needs:
      - dev-deps
    if: '!github.event.pull_request.draft'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: 🧪 Run tests
        run: nix build ".#checks.$(nix eval --impure --expr 'builtins.currentSystem').tests"
      - name: 🧪 Run tests for external solver CaDiCaL
        run: nix build ".#checks.$(nix eval --impure --expr 'builtins.currentSystem').externalCadical"
      - name: 🧪 Run tests for external solver Kissat
        run: nix build ".#checks.$(nix eval --impure --expr 'builtins.currentSystem').externalKissat"
      - name: 🧪 Run tests for external solver Gimsatul
        run: nix build ".#checks.$(nix eval --impure --expr 'builtins.currentSystem').externalGimsatul"
  msrv-build:
    name: 🏗️ MSRV build
    runs-on: [self-hosted, nix]
    if: '!github.event.pull_request.draft'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: 🏗️ Check MSRV builds
        run: nix build ".#checks.$(nix eval --impure --expr 'builtins.currentSystem').msrv"
  wasm-check:
    name: 🏄 WASM check
    runs-on: [self-hosted, nix]
    if: '!github.event.pull_request.draft'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: 🏄 Check WASM compatibility
        run: nix build ".#checks.$(nix eval --impure --expr 'builtins.currentSystem').wasm"
  code-quality:
    name: ✨ Code Quality
    runs-on: [self-hosted, nix]
    needs:
      - dev-deps
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: ✨ Check formatting
        run: nix build ".#checks.$(nix eval --impure --expr 'builtins.currentSystem').treefmt"
      - name: ✨ Cargo deny bans licenses sources
        run: nix build ".#checks.$(nix eval --impure --expr 'builtins.currentSystem').deny"
      - name: ✨ Cargo deny advisories
        run: nix develop ".#cargoDeny" --command cargo deny --exclude-unpublished --exclude-dev check advisories
      - name: ✨ Cargo machete
        run: nix build ".#checks.$(nix eval --impure --expr 'builtins.currentSystem').machete"
      - name: ✨ Cargo clippy
        run: nix build ".#checks.$(nix eval --impure --expr 'builtins.currentSystem').clippy"
      - name: ✨ Check typos
        run: nix build ".#checks.$(nix eval --impure --expr 'builtins.currentSystem').typos"
      - name: ✨ Check spelling
        run: nix build ".#checks.$(nix eval --impure --expr 'builtins.currentSystem').spellcheck"
      - name: ✨ Check generated readmes
        run: nix build ".#checks.$(nix eval --impure --expr 'builtins.currentSystem').readmes"
      - name: ✨ Check generated code
        run: nix build ".#checks.$(nix eval --impure --expr 'builtins.currentSystem').codegen"
  python-api:
    name: 🐍 Python API
    runs-on: [self-hosted, nix]
    if: '!github.event.pull_request.draft'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: ✨ Build Python API and check
        run: nix build ".#checks.$(nix eval --impure --expr 'builtins.currentSystem').pyapi"
  doc:
    name: 📑 Check documentation
    runs-on: [self-hosted, nix]
    needs:
      - dev-deps
    if: '!github.event.pull_request.draft'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: ✨ Build doc
        run: nix build ".#checks.$(nix eval --impure --expr 'builtins.currentSystem').doc"
      - name: 🧪 Run doc tests
        run: nix build ".#checks.$(nix eval --impure --expr 'builtins.currentSystem').docTests"
  coverage:
    name: 📋 Test coverage
    runs-on: [self-hosted, nix]
    needs:
      - tests
      - doc
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: ✨ Collect coverage reports
        run: |
          nix build .#testCoverage
          mkdir -p coverage
          cp result/*.lcov coverage
          rm result
      - name: ✨ Publish to Coveralls
        run: nix run --inputs-from . nur-packages#coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # TODO: Kani
  feature-powerset:
    name: 🔌 Test feature powerset
    runs-on: [self-hosted, nix]
    needs:
      - dev-deps
    if: "!github.event.pull_request.draft && contains(github.event.pull_request.labels.*.name, 'heavy-tests')"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: ✨ Run feature powerset checks
        run: nix build ".#checks.$(nix eval --impure --expr 'builtins.currentSystem').featurePowerset"
  cadical-each-feature:
    name: 🧪 CaDiCaL test each feature
    runs-on: [self-hosted, nix]
    needs:
      - dev-deps
    if: "!github.event.pull_request.draft && contains(github.event.pull_request.labels.*.name, 'solvers/cadical')"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: 🧪 Test each feature
        run: nix develop ".#ci" --command cargo hack --each-feature --clean-per-run --exclude-features logging nextest run -p rustsat-cadical
  kissat-each-feature:
    name: 🧪 Kissat test each feature
    runs-on: [self-hosted, nix]
    needs:
      - dev-deps
    if: "!github.event.pull_request.draft && contains(github.event.pull_request.labels.*.name, 'solvers/kissat')"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: 🧪 Test each feature
        run: nix develop ".#ci" --command cargo hack --each-feature --clean-per-run nextest run -p rustsat-kissat
