name: Docs

on:
  push:
    branches: [ "main", "next-major" ]
  pull_request:
    branches: [ "main", "next-major" ]

env:
  CARGO_TERM_COLOR: always
  RUSTDOCFLAGS: "-Dwarnings"

jobs:
  doc:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-spellcheck
        uses: taiki-e/install-action@cargo-spellcheck
      - name: Run cargo doc
        run: cargo doc --workspace --verbose --no-deps --features=all
      - name: Run doc tests
        run: cargo test --doc --workspace
      - name: Spellcheck documentation
        run: cargo spellcheck --code 1
      - name: Check READMEs
        run: |
          cargo install cargo-rdme
          return=true
          if ! cargo rdme --check; then
            echo "failed for main crate"
            return=false
          fi
          for dir in tools cadical kissat minisat glucose batsat ipasir capi pyapi pigeons; do
            cd ${dir}
            if ! cargo rdme --check; then
              echo "failed for ${dir}"
              return=false
            fi
            cd ..
          done
          ${return}
