name: IPASIR

on:
  push:
    branches: [ "main", "next-major" ]
  pull_request:
    branches: [ "main", "next-major" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "build-test"
      - name: Cargo build
        run: cargo build -p rustsat-ipasir --verbose
        env:
          CMAKE_BUILD_PARALLEL_LEVEL: ${{ fromJSON('["", "4"]')[matrix.os == 'macos-latest'] }}
