name: "Pull Request Labeler"

on:
  pull_request_target:

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: self-hosted
    steps:
    - uses: actions/labeler@v5
