name: Pigeons

on:
  push:
    branches: [ "main", "next-major" ]
  pull_request:
    branches: [ "main", "next-major" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    name: Build and test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "build-test"
      - name: Install latest nextest release
        uses: taiki-e/install-action@nextest
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install VeriPB
        if: matrix.os == 'ubuntu-latest'
        run: >
          sudo apt-get install libgmp-dev &&
          pip install https://gitlab.com/MIAOresearch/software/VeriPB/-/archive/version2/VeriPB-version2.zip &&
          export VERIPB_CHECKER=$(which veripb)
      - name: Cargo build
        run: cargo build -p pigeons --verbose
        env:
          CMAKE_BUILD_PARALLEL_LEVEL: ${{ fromJSON('["", "4"]')[matrix.os == 'macos-latest'] }}
      - name: Cargo test
        run: cargo nextest run --profile ci -p pigeons --verbose
        env:
          CMAKE_BUILD_PARALLEL_LEVEL: ${{ fromJSON('["", "4"]')[matrix.os == 'macos-latest'] }}
