name: RustSAT

on:
  push:
    branches: [ "main", "next-major" ]
  pull_request:
    branches: [ "main", "next-major" ]

env:
  CARGO_TERM_COLOR: always
    
jobs:
  build-test:
    name: Build and test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "build-test"
      - name: Cargo build
        run: cargo build -p rustsat --verbose --features=all
        env:
          CMAKE_BUILD_PARALLEL_LEVEL: ${{ fromJSON('["", "4"]')[matrix.os == 'macos-latest'] }}
      - name: Cargo test
        run: cargo test -p rustsat --verbose --features=all
        env:
          CMAKE_BUILD_PARALLEL_LEVEL: ${{ fromJSON('["", "4"]')[matrix.os == 'macos-latest'] }}
      - name: CaDiCaL external solver
        if: matrix.os == 'ubuntu-latest'
        run: |
          curl -O https://media.christophjabs.info/cadical-2-0-0
          chmod +x cadical-2-0-0
          RS_EXT_SOLVER=./cadical-2-0-0 cargo test --test external_solver --verbose -- --ignored
      - name: Kissat external solver
        if: matrix.os == 'ubuntu-latest'
        run: |
          curl -O https://media.christophjabs.info/kissat-3-1-1
          chmod +x kissat-3-1-1
          RS_EXT_SOLVER=./kissat-3-1-1 cargo test --test external_solver --verbose -- --ignored
      - name: Gimsatul external solver
        if: matrix.os == 'ubuntu-latest'
        run: |
          curl -O https://media.christophjabs.info/gimsatul-1-1-2
          chmod +x gimsatul-1-1-2
          RS_EXT_SOLVER=./gimsatul-1-1-2 cargo test --test external_solver --verbose -- --ignored

  kani:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Cargo kani
        uses: model-checking/kani-github-action@v1
        with:
          args: '-p rustsat'

