name: Semver checks
on:
  pull_request:
    branches: ["main"]
    types: [review_requested, ready_for_review]
env:
  CARGO_TERM_COLOR: always
jobs:
  all:
    name: 🛡️ Semver checks
    runs-on: [self-hosted, nix]
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: 🛡️ Run semver checks
        run: nix run nixpkgs#just semver-checks
