name: Semver checks
on:
  pull_request:
    branches: ["main"]
    types: [review_requested, ready_for_review]
env:
  CARGO_TERM_COLOR: always
jobs:
  all:
    name: 🛡️ Semver checks
    runs-on: [self-hosted, nix]
    steps:
      - uses: actions/checkout@v4
      - name: 🛡️ Run semver checks
        run: nix build --impure ".#checks.$(nix eval --impure --expr 'builtins.currentSystem').semverChecks"
