name: Semver checks
on:
  pull_request:
    branches: ["main"]
    types: [review_requested, ready_for_review]
env:
  CARGO_TERM_COLOR: always
jobs:
  all:
    name: 🛡️ Semver checks
    runs-on: [self-hosted, nix]
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: 🛡️ Run semver checks
        run: nix run nixpkgs#just semver-checks
