// Auto-generated by codegen, do not edit manually

#![no_main]

use libfuzzer_sys::fuzz_target;
use rustsat::{encodings::am1::Bitwise, types::Lit};
use rustsat_fuzz::{am1, Lit16};

fuzz_target!(|input: (Vec<Lit16>, u64)| {
    let lits: Vec<_> = input.0.into_iter().map(Lit::from).collect();
    am1::<Bitwise>(&lits, input.1)
});
