// Auto-generated by codegen, do not edit manually

use afl::fuzz;
use rustsat::{encodings::am1::Commander, types::Lit};
use rustsat_fuzz::{am1, Lit16};

fn main() {
    fuzz!(|input: (Vec<Lit16>, u64)| {
        let lits: Vec<_> = input.0.into_iter().map(Lit::from).collect();
        am1::<Commander>(&lits, input.1)
    });
}
